version: "3.9"

services:
  postgresDb:
    image: postgres
    container_name: bookstore_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookstore
    volumes:
      - pgData:./var/postgres/data

volumes:
  pgData:
